apiVersion: v1
kind: Service
metadata:
  name: store-service
spec:
  type: NodePort
  selector:
    app: store
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    nodePort: 30080
    protocol: TCP
