name: publish-arm-image.yml
on:
  push:
    branches: [ "master" ]

jobs:
  build:
    uses: ./.github/workflows/build-and-test.yml

  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate image version
        run: echo "ARM-1.${GITHUB_RUN_NUMBER}"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

#      - name: Login to Docker Hub
#        run: docker login -u ${{ secrets.DOCKER_HUB_USER }} -p ${{ secrets.DOCKER_HUB_TOKEN }}